# Generated by Django 5.1.6 on 2025-04-07 14:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedEmail',
            fields=[
                ('sharedemail_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('submit_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
