# Generated by Django 5.1.6 on 2025-04-13 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleCalculation',
            fields=[
                ('simplecalculation_id', models.AutoField(primary_key=True, serialize=False)),
                ('expected_grad_date', models.DateTimeField()),
                ('loan_amount', models.CharField(max_length=100)),
                ('submit_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
