# Generated by Django 5.1.6 on 2025-04-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
