# Generated by Django 5.1.6 on 2025-04-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_referrals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Referrals',
            new_name='Referral',
        ),
    ]
