# Generated by Django 5.1.6 on 2025-04-14 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_simplecalculation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Referral',
            new_name='EmailList',
        ),
        migrations.RenameField(
            model_name='emaillist',
            old_name='referral_id',
            new_name='emaillist_id',
        ),
    ]
